import Head from 'next/head'
import tw from 'twin.macro'
import Card from '../components/card'

export default function Home() {
  return (
    <div tw="flex items-center justify-center min-h-screen bg-black">
      <Head>
        <title>Frontend Mentor | Interactive rating component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card />
    </div>
  )
}
